trusted : [10.0.0.1:8001,10.0.0.2:8002,10.0.0.3:8003,10.0.0.4:8004,10.0.0.5:8005] #trusted ip + port
faulty : [] #faulty ip + port
algorithm : 11 #[1,2,3,4...,11]
source_byzantine : true #[true, false]
data_size : 1024 #size is bytes
rounds : 2000 # number of data reliable broadcast from the source
faulty_behavior : wrong_message #Could be extended in the future for certain faulty behaviour