trusted : [127.0.0.1:8001,127.0.0.1:8002,127.0.0.1:8003,127.0.0.1:8004,127.0.0.1:8005] #trusted ip + port
faulty : [] #faulty ip + port
algorithm : 1 #[1,2,3,4...,8]
source_byzantine : false #[true, false]
data_size : 100 #size is bytes
rounds : 70 # number of data reliable broadcast from the source
faulty_behavior : wrong_message #Could be extended in the future for certain faulty behaviour