topology: EvalSmartHome # [ EvalSmartHome, LinearTopo, CustomTree, CustomFatTree, SingleSwitchSlowSrc, TreeTopo ]

# A topology that simulates an IoT smart home setting
smart_home:
  k: 40 # number of nodes (hosts)
  bw: 50000000 # bandwidth (bytes/s)
  delay: '10ms'
  jitter: '3ms'
  loss: 2 # %

# Mininet's LinearTopo (total_hosts = k*n)
linear_topo:
  k: 5 # number of switches
  n: 1 # number of hosts per switch

# topologies/CustomTree.py
custom_tree:
  depth: 3
  fanout: 2
  total_hosts: 5

# topologies/CustomFatTree.py (total_hosts = e*n)
custom_fat_tree:
  e: 5 # number of edge switches
  n: 1 # number of hosts per switch

# topologies/SingleSwitchSlowSrc.py (total_hosts = k)
single_switch_slow_src:
  k: 5
  bw_src: 0.5 # Bandwidth of the source node

# Mininet's TreeTopo (total_hosts = fanout**depth)
tree_topo:
  depth: 3
  fanout: 2